{
    ["databars"] = {
        ["artifact"] = {
            ["height"] = 176,
        },
        ["reputation"] = {
            ["enable"] = true,
            ["height"] = 10,
            ["orientation"] = "HORIZONTAL",
            ["width"] = 178,
        },
        ["honor"] = {
            ["enable"] = false,
            ["height"] = 176,
        },
    },
    ["currentTutorial"] = 9,
    ["general"] = {
        ["totems"] = {
            ["enable"] = false,
        },
        ["fontSize"] = 13,
        ["hideErrorFrame"] = false,
        ["autoAcceptInvite"] = true,
        ["afk"] = false,
        ["autoRepair"] = "GUILD",
        ["minimap"] = {
            ["icons"] = {
                ["lfgEye"] = {
                    ["yOffset"] = -7,
                    ["position"] = "TOP",
                },
                ["classHall"] = {
                    ["xOffset"] = -5,
                    ["position"] = "LEFT",
                },
            },
            ["locationText"] = "SHOW",
            ["size"] = 250,
        },
        ["bottomPanel"] = false,
        ["backdropfadecolor"] = {
            ["b"] = 0.054,
            ["g"] = 0.054,
            ["r"] = 0.054,
        },
        ["numberPrefixStyle"] = "CHINESE",
        ["loginmessage"] = false,
        ["threat"] = {
            ["enable"] = false,
        },
        ["topPanel"] = false,
        ["font"] = "聊天",
        ["vendorGrays"] = true,
        ["objectiveFrameHeight"] = 550,
        ["interruptAnnounce"] = "PARTY",
        ["valuecolor"] = {
            ["r"] = 0.09,
            ["g"] = 0.513,
            ["b"] = 0.819,
        },
    },
    ["bossAuraFiltersConverted"] = true,
    ["hideTutorial"] = true,
    ["chat"] = {
        ["chatHistory"] = false,
        ["emotionIcons"] = false,
        ["tabFont"] = "聊天",
        ["keywords"] = "",
        ["tabFontSize"] = 14,
        ["panelHeight"] = 210,
        ["font"] = "聊天",
        ["noAlertInCombat"] = true,
        ["fontOutline"] = "OUTLINE",
        ["fadeTabsNoBackdrop"] = false,
        ["tabFontOutline"] = "OUTLINE",
        ["editBoxPosition"] = "ABOVE_CHAT",
        ["panelBackdrop"] = "LEFT",
    },
    ["layoutSet"] = "healer",
    ["bagSortIgnoreItemsReset"] = true,
    ["movers"] = {
        ["RaidMarkerBarAnchor"] = "TOP,ElvUIParent,TOP,0,-4",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,275",
        ["ElvUF_RaidMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,488",
        ["ElvUF_FocusTargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,59,200",
        ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,215,-4",
        ["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-257,-17",
        ["BossButton"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-540,-447",
        ["LootFrameMover"] = "TOP,ElvUIParent,TOP,0,-197",
        ["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,736",
        ["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,-59,200",
        ["OzCooldownsMover"] = "BOTTOM,ElvUIParent,BOTTOM,-181,284",
        ["VehicleSeatMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-257,-181",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-511,285",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,244,285",
        ["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,91",
        ["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-491",
        ["ElvUF_Raid40Mover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,409",
        ["ElvUF_PetMover"] = "BOTTOM,ElvUIParent,BOTTOM,-152,240",
        ["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,398",
        ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,4",
        ["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,0,32",
        ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,240",
        ["LocationLiteMover"] = "TOP,ElvUIParent,TOP,0,-4",
        ["TalkingHeadFrameMover"] = "TOP,ElvUIParent,TOP,0,-32",
        ["MinimapButtonAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-273",
        ["AltPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,120",
        ["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,0,60",
        ["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-36,-275",
        ["ArtifactBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,418,21",
        ["FarmSeedAnchor"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-251",
        ["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,244,317",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-85,-307",
        ["BNETMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,212",
        ["ShiftAB"] = "TOPRIGHT,ElvUIParent,BOTTOMLEFT,464,195",
        ["ElvAB_5"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,0,299",
        ["HonorBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-430,4",
        ["ArenaHeaderMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,375,-259",
        ["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-55,268",
        ["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,563",
        ["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-347,-381",
        ["TotemBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-434,19",
        ["ElvAB_4"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-41,299",
        ["ElvUF_PartyMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,615,365",
        ["AlertFrameMover"] = "TOP,ElvUIParent,TOP,0,-269",
        ["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-257,-127",
        ["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,630",
    },
    ["tooltip"] = {
        ["itemCount"] = "BOTH",
        ["healthBar"] = {
            ["height"] = 14,
            ["fontSize"] = 14,
            ["font"] = "聊天",
        },
        ["headerFontSize"] = 14,
        ["textFontSize"] = 13,
        ["font"] = "聊天",
        ["fontOutline"] = "OUTLINE",
        ["progressInfo"] = false,
        ["smallTextFontSize"] = 14,
    },
    ["auras"] = {
        ["countXOffset"] = 2,
        ["debuffs"] = {
            ["size"] = 36,
        },
        ["fontSize"] = 16,
        ["fontOutline"] = "OUTLINE",
        ["buffs"] = {
            ["size"] = 36,
            ["maxWraps"] = 2,
        },
        ["countYOffset"] = 20,
        ["timeYOffset"] = 7,
        ["font"] = "伤害数字",
    },
    ["bags"] = {
        ["countFontSize"] = 12,
        ["yOffsetBank"] = 180,
        ["itemLevelFont"] = "聊天",
        ["xOffsetBank"] = -3,
        ["ignoreItems"] = "",
        ["itemLevelFontSize"] = 14,
        ["alignToChat"] = false,
        ["bagWidth"] = 410,
        ["countFont"] = "聊天",
        ["countFontOutline"] = "OUTLINE",
        ["bankWidth"] = 400,
        ["itemLevelFontOutline"] = "OUTLINE",
        ["xOffset"] = -34,
        ["junkIcon"] = true,
    },
    ["unitframe"] = {
        ["auraBlacklistModifier"] = "NONE",
        ["smoothbars"] = true,
        ["colors"] = {
            ["auraBarBuff"] = {
                ["r"] = 0.1,
                ["g"] = 0.1,
                ["b"] = 0.1,
            },
            ["colorhealthbyvalue"] = false,
            ["castClassColor"] = true,
            ["transparentPower"] = true,
            ["castColor"] = {
                ["r"] = 0.1,
                ["g"] = 0.1,
                ["b"] = 0.1,
            },
            ["transparentCastbar"] = true,
            ["health"] = {
                ["r"] = 0.30980392156863,
                ["g"] = 0.30980392156863,
                ["b"] = 0.30980392156863,
            },
            ["classbackdrop"] = true,
            ["transparentHealth"] = true,
            ["health_backdrop_dead"] = {
                ["b"] = 0.007843137254902,
                ["g"] = 0.007843137254902,
                ["r"] = 0.41176470588235,
            },
        },
        ["font"] = "聊天",
        ["units"] = {
            ["pet"] = {
                ["debuffs"] = {
                    ["enable"] = true,
                },
                ["portrait"] = {
                    ["xOffset"] = 0.01,
                    ["width"] = 59,
                },
                ["castbar"] = {
                    ["height"] = 10,
                    ["latency"] = false,
                },
                ["width"] = 80,
                ["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
                ["name"] = {
                    ["yOffset"] = 8,
                },
                ["buffs"] = {
                    ["enable"] = true,
                },
                ["height"] = 16,
                ["power"] = {
                    ["height"] = 3,
                },
            },
            ["raid"] = {
                ["horizontalSpacing"] = 2,
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["sizeOverride"] = 16,
                    ["enable"] = true,
                    ["xOffset"] = -4,
                    ["yOffset"] = -7,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                },
                ["growthDirection"] = "DOWN_RIGHT",
                ["healPrediction"] = true,
                ["width"] = 65,
                ["health"] = {
                    ["frequentUpdates"] = true,
                },
                ["power"] = {
                    ["height"] = 4,
                },
                ["height"] = 30,
                ["buffs"] = {
                    ["sizeOverride"] = 22,
                    ["useBlacklist"] = false,
                    ["noDuration"] = false,
                    ["playerOnly"] = false,
                    ["yOffset"] = -6,
                    ["clickThrough"] = true,
                    ["enable"] = true,
                    ["useFilter"] = "TurtleBuffs",
                    ["perrow"] = 1,
                    ["xOffset"] = 50,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["yOffset"] = 0,
                },
            },
            ["focustarget"] = {
                ["power"] = {
                    ["enable"] = true,
                    ["height"] = 3,
                },
                ["enable"] = true,
                ["width"] = 100,
                ["height"] = 16,
            },
            ["targettarget"] = {
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["perrow"] = 6,
                },
                ["threatStyle"] = "BORDERS",
                ["power"] = {
                    ["height"] = 3,
                },
                ["width"] = 90,
                ["name"] = {
                    ["yOffset"] = 8,
                },
                ["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
                ["height"] = 16,
                ["buffs"] = {
                    ["enable"] = true,
                    ["perrow"] = 6,
                },
            },
            ["player"] = {
                ["debuffs"] = {
                    ["sizeOverride"] = 0,
                },
                ["castbar"] = {
                    ["width"] = 220,
                },
                ["power"] = {
                    ["height"] = 3,
                    ["yOffset"] = 12,
                },
                ["width"] = 220,
                ["health"] = {
                    ["xOffset"] = 16,
                    ["yOffset"] = 12,
                },
                ["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
                ["height"] = 16,
                ["buffs"] = {
                    ["attachTo"] = "FRAME",
                    ["sizeOverride"] = 0,
                },
                ["classbar"] = {
                    ["height"] = 3,
                    ["autoHide"] = true,
                },
            },
            ["raid40"] = {
                ["growthDirection"] = "DOWN_RIGHT",
                ["roleIcon"] = {
                    ["attachTo"] = "Frame",
                    ["position"] = "TOPLEFT",
                    ["enable"] = true,
                    ["xOffset"] = 0,
                    ["size"] = 12,
                },
                ["raidWideSorting"] = false,
                ["power"] = {
                    ["enable"] = true,
                    ["height"] = 4,
                },
                ["healPrediction"] = true,
                ["width"] = 66,
                ["health"] = {
                    ["frequentUpdates"] = true,
                },
                ["height"] = 34,
                ["invertGroupingOrder"] = false,
            },
            ["focus"] = {
                ["castbar"] = {
                    ["height"] = 10,
                    ["width"] = 100,
                },
                ["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
                ["width"] = 100,
                ["power"] = {
                    ["height"] = 3,
                },
                ["height"] = 16,
            },
            ["target"] = {
                ["debuffs"] = {
                    ["attachTo"] = "FRAME",
                    ["sizeOverride"] = 0,
                },
                ["smartAuraDisplay"] = "DISABLED",
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["castbar"] = {
                    ["height"] = 10,
                    ["latency"] = true,
                    ["width"] = 220,
                },
                ["name"] = {
                    ["attachTextTo"] = "Frame",
                    ["yOffset"] = 12,
                    ["position"] = "TOP",
                },
                ["power"] = {
                    ["height"] = 3,
                    ["position"] = "TOPRIGHT",
                },
                ["width"] = 220,
                ["middleClickFocus"] = false,
                ["health"] = {
                    ["xOffset"] = 0,
                    ["yOffset"] = 12,
                    ["position"] = "LEFT",
                },
                ["height"] = 16,
                ["buffs"] = {
                    ["numrows"] = 2,
                    ["perrow"] = 9,
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["sizeOverride"] = 0,
                },
                ["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
            },
            ["arena"] = {
                ["power"] = {
                    ["height"] = 4,
                },
            },
            ["boss"] = {
                ["debuffs"] = {
                    ["yOffset"] = 0,
                },
                ["width"] = 191,
                ["height"] = 37,
                ["power"] = {
                    ["height"] = 4,
                },
            },
            ["party"] = {
                ["horizontalSpacing"] = 2,
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["sizeOverride"] = 16,
                    ["xOffset"] = -4,
                    ["perrow"] = 3,
                    ["yOffset"] = -7,
                },
                ["numGroups"] = 5,
                ["growthDirection"] = "DOWN_RIGHT",
                ["roleIcon"] = {
                    ["xOffset"] = 1,
                    ["position"] = "TOPLEFT",
                    ["yOffset"] = -1,
                },
                ["power"] = {
                    ["height"] = 4,
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = 2,
                },
                ["GPSArrow"] = {
                    ["enable"] = false,
                    ["size"] = 40,
                },
                ["healPrediction"] = true,
                ["width"] = 65,
                ["infoPanel"] = {
                    ["height"] = 12,
                },
                ["orientation"] = "MIDDLE",
                ["name"] = {
                    ["text_format"] = "[namecolor][name:short]",
                },
                ["health"] = {
                    ["frequentUpdates"] = true,
                    ["position"] = "BOTTOM",
                    ["xOffset"] = 0,
                    ["text_format"] = "[healthcolor][health:deficit]",
                    ["yOffset"] = 2,
                },
                ["height"] = 30,
                ["buffs"] = {
                    ["sizeOverride"] = 22,
                    ["useBlacklist"] = false,
                    ["noDuration"] = false,
                    ["playerOnly"] = false,
                    ["yOffset"] = -6,
                    ["clickThrough"] = true,
                    ["enable"] = true,
                    ["useFilter"] = "TurtleBuffs",
                    ["perrow"] = 1,
                    ["xOffset"] = 50,
                },
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["yOffset"] = 0,
                },
            },
        },
    },
    ["datatexts"] = {
        ["minimapTop"] = true,
        ["goldCoins"] = true,
        ["minimapBottom"] = true,
        ["goldFormat"] = "FULL",
        ["time24"] = true,
        ["panels"] = {
            ["BottomMiniPanel"] = "Time",
            ["LeftChatDataPanel"] = {
                ["right"] = "Durability",
                ["left"] = "System",
                ["middle"] = "Talent/Loot Specialization",
            },
            ["RightChatDataPanel"] = {
                ["middle"] = "Skada",
                ["left"] = "Item Level",
            },
        },
        ["font"] = "聊天",
        ["fontOutline"] = "OUTLINE",
        ["localtime"] = false,
        ["battleground"] = false,
    },
    ["actionbar"] = {
        ["bar3"] = {
            ["inheritGlobalFade"] = true,
            ["buttons"] = 12,
            ["buttonspacing"] = 1,
            ["buttonsPerRow"] = 12,
            ["buttonsize"] = 26,
        },
        ["fontSize"] = 12,
        ["bar2"] = {
            ["enabled"] = true,
            ["inheritGlobalFade"] = true,
            ["buttonspacing"] = 1,
            ["buttonsize"] = 26,
        },
        ["bar1"] = {
            ["buttonspacing"] = 1,
            ["inheritGlobalFade"] = true,
            ["buttonsize"] = 26,
        },
        ["bar4"] = {
            ["enabled"] = false,
            ["point"] = "BOTTOMLEFT",
            ["alpha"] = 0.5,
            ["showGrid"] = false,
            ["buttonsize"] = 26,
            ["backdrop"] = false,
        },
        ["bar5"] = {
            ["point"] = "TOPLEFT",
            ["buttons"] = 12,
            ["buttonspacing"] = 0,
            ["buttonsPerRow"] = 1,
            ["buttonsize"] = 26,
        },
        ["fontOutline"] = "OUTLINE",
        ["font"] = "伤害数字",
        ["macrotext"] = true,
        ["stanceBar"] = {
            ["buttonsPerRow"] = 1,
            ["inheritGlobalFade"] = true,
            ["point"] = "TOPRIGHT",
            ["buttons"] = 5,
        },
        ["barPet"] = {
            ["inheritGlobalFade"] = true,
            ["point"] = "BOTTOMLEFT",
            ["buttonspacing"] = 1,
            ["buttonsPerRow"] = 10,
            ["backdrop"] = false,
            ["buttonsize"] = 24,
        },
        ["backdropSpacingConverted"] = true,
    },
    ["nameplates"] = {
        ["useTargetScale"] = false,
        ["fontOutline"] = "OUTLINE",
        ["font"] = "聊天",
        ["fontSize"] = 10,
    },
    ["cooldown"] = {
        ["threshold"] = 5,
    },
    ["RS"] = {
        ["misc"] = {
            ["automation"] = false,
        },
    },
}::profile::小清水亞美 - 巫妖之王